spring:
#  profiles:
#    active: dev
  application:
    name: vendas
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
#  config:
#    activate:
#      on-profile: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:vendasII}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:root}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

  jackson:
    deserialization:
      fail-on-unknown-properties: true

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: 463938c54f3b25
    password: 8ab42b32d0e4ef
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  web:
    resources:
      static-locations: classpath:/static/

jwt:
  expiracao: 30
  refresh-expiracao: 1440

#logging:
#  level:
#    org.springframework.security: DEBUG
#    io.jsonwebtoken: DEBUG

web:
  resources:
    static-locations=classpath:/static/,file:///E:/dev/projetos/vendas/back-end-vendas/images/:

