CREATE TABLE IF NOT EXISTS documentos_assinados (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  usuario_id BIGINT NOT NULL,
  nome_arquivo VARCHAR(255) NOT NULL,
  conteudo LONGBLOB NOT NULL,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE
);
