CREATE TABLE CATEGORIA (
  codigo BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,  -- Add this line
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP  -- Add this line
) ENGINE=InnoDB DEFAULT CHARSET=utf8;